name: Sonatype SCA Scanning for CDM

on:
  workflow_dispatch:
  pull_request_target:
  push:

env:
  SonatypeUrl: "https://finos.sonatype.app/platform/"
  SonatypeAppId: "common-domain-model"
  ExcludeDirectory: ""

jobs:
  scan-java:
    name: Build and Scan with Sonatype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          cache: maven
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      
      - name: Build with Maven
        run: |
          mvn -B -U clean package -Dmaven.test.skip=true
        # mvn clean install -Dmaven.test.skip=true
          
      - name: Sonatype Lifecycle SCA Scan
        if: always()
        # if: github.repository_owner == 'finos'
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          stage: "build"
          scan-targets: .
          module-exclude: ${{ env.ExcludeDirectory }}
          
      - name: Save Sonatype SBOM
        if: steps.evaluate.outputs.scan-id && always() 
        uses: sonatype/actions/fetch-sbom@v1
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          scan-id: ${{ steps.evaluate.outputs.scan-id }}
          sbom-standard: spdx
          sbom-version: 2.3
          artifact-name: ${{ env.SonatypeAppId }}-sonatype-bom
          
